# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7"

# sudo and dist are required so that Python 3.7
# can be used, this is the official way to do it.
# See: github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox-travis

# command to run tests, e.g. python setup.py test
script: tox -r

after_success:
  - pip install coveralls
  - coveralls
